version: "3.2"

services:
  ros2-talker:
    image: ros:foxy
    command: >-
      ros2 topic pub /chatter std_msgs/msg/Int32 '{data: 1}' -r 1
    volumes:
      - type: bind
        source: ./fastrtps.xml
        target: /opt/fastrtps.xml
      - type: bind 
        source: /dev 
        target: /dev 
      - type: bind
        source: /tmp
        target: /tmp
    env_file: ros.env
    ipc: host
    network_mode: host
    init: true
    pid: host
    tty: true
  ros2-listener:
    image: ros:foxy
    command: >-
      ros2 topic echo /chatter std_msgs/msg/Int32
    depends_on:
      - ros2-talker
    ipc: host
    pid: host
    volumes:
      - type: bind
        source: ./fastrtps.xml
        target: /opt/fastrtps.xml
      - type: bind 
        source: /dev 
        target: /dev 
      - type: bind
        source: /tmp
        target: /tmp
    env_file: ros.env
    network_mode: host
    init: true
    tty: true
