version: "3.2"

services:
  ros2-talker:
    container_name: ros2-talker
    image: ros:galactic
    init: true
    tty: true
    command: >-
      ros2 topic pub /chatter std_msgs/msg/Int32 '{data: 1}'
  ros2-listener:
    container_name: ros2-listener
    image: ros:galactic
    init: true
    tty: true
    command: >-
      ros2 topic echo /chatter
    depends_on:
      - ros2-talker
