services:
  ros2-talker:
    build: ./
    command: ros2 run demo_nodes_cpp talker
    ipc: host
    environment:
      RMW_IMPLEMENTATION: rmw_connextdds
      NDDS_QOS_PROFILES: /shared-mem-qos.xml
    volumes:
      - ./shared-mem-qos.xml:/shared-mem-qos.xml
  ros2-listener:
    build: ./
    command: ros2 run demo_nodes_cpp listener
    ipc: host
    environment:
      RMW_IMPLEMENTATION: rmw_connextdds
      NDDS_QOS_PROFILES: /shared-mem-qos.xml
    volumes:
      - ./shared-mem-qos.xml:/shared-mem-qos.xml