services:
  ros2-talker:
    build: ./
    command: ros2 run demo_nodes_cpp talker
    ipc: host
    network_mode: host
    # environment:
      # https://fast-dds.docs.eprosima.com/en/latest/fastdds/ros2/ros2_configure.html
      # FASTRTPS_DEFAULT_PROFILES_FILE: ./fastdds-qos.xml
      # RMW_FASTRTPS_USE_QOS_FROM_XML: 1
    # volumes:
    #   - ./fastdds-qos.xml:/fastdds-qos.xml
  ros2-listener:
    build: ./
    command: ros2 run demo_nodes_cpp listener
    ipc: host
    network_mode: host
    # environment:
      # FASTRTPS_DEFAULT_PROFILES_FILE: ./fastdds-qos.xml
      # RMW_FASTRTPS_USE_QOS_FROM_XML: 1
    # volumes:
    #   - ./fastdds-qos.xml:/fastdds-qos.xml